import 'package:flutter/material.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse11Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse12Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse13Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse1Widget3.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedEllipse8Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedprofilewidget/generated/GeneratedProjyWidget3.dart';

/* Component profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 896.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 135, 134, 231),
                              ),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 71.0,
                              child: GeneratedEllipse1Widget3(),
                            ),
                            Positioned(
                              left: 281.0,
                              top: -138.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 207.0,
                              child: GeneratedEllipse8Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 22.0,
                              child: GeneratedEllipse2Widget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 157.00,
                                  y: -416.00,
                                  z: 0,
                                  child: GeneratedProjyWidget3()),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 37.0,
                              child: GeneratedEllipse11Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 26.0,
                              child: GeneratedEllipse12Widget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: GeneratedEllipse13Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
