import 'package:flutter/material.dart';
import 'package:projyproject/shared/menu_drawer.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedProjyWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup13Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup7Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup9Widget.dart';

/* Component updateprofilescreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUpdateprofilescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var scaffoldKey = GlobalKey<ScaffoldState>();
    return Scaffold(
        drawer: ClipRRect(
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(1000),
              bottomRight: Radius.circular(10)),
          child: MenuDrawer(),
        ),
        appBar: AppBar(
            key: scaffoldKey,
            leading: Builder(
              builder: (context) => IconButton(
                icon: Icon(Icons.menu_rounded),
                iconSize: 40,
                onPressed: () => Scaffold.of(context).openDrawer(),
              ),
            ),
            flexibleSpace: Container(
              decoration: new BoxDecoration(
                gradient: new LinearGradient(
                    colors: [
                      Color.fromARGB(255, 102, 59, 223),
                      Color.fromARGB(255, 135, 134, 231),
                    ],
                    begin: const FractionalOffset(0.0, 0.0),
                    end: const FractionalOffset(1.0, 0.0),
                    stops: [0.0, 1.0],
                    tileMode: TileMode.clamp),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                    ),
                    Positioned(
                      left: null,
                      top: -110,
                      right: -68.0,
                      bottom: null,
                      width: 192.0,
                      height: 207.0,
                      child: GeneratedEllipse8Widget(),
                    ),
                    Positioned(
                      left: null,
                      top: 40,
                      right: -4.8552703857421875,
                      bottom: null,
                      width: 96.85527038574219,
                      height: 44.0,
                      child: GeneratedProjyWidget(),
                    ),
                  ]),
            )),
        body: Material(
            child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 966.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 423.0,
                          height: 966.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 135, 134, 231),
                                  ),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: null,
                                  bottom: null,
                                  width: 386.0,
                                  height: 612.0,
                                  child: TransformHelper.translate(
                                      x: -0.50,
                                      y: -40,
                                      z: 0,
                                      child: GeneratedGroup7Widget()),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: null,
                                  bottom: null,
                                  width: 261.0,
                                  height: 69.0,
                                  child: TransformHelper.translate(
                                      x: 0.00,
                                      y: 305,
                                      z: 0,
                                      child: GeneratedGroup9Widget()),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: null,
                                  bottom: null,
                                  width: 253.0,
                                  height: 57.0,
                                  child: TransformHelper.translate(
                                      x: 0.00,
                                      y: 380,
                                      z: 0,
                                      child: GeneratedGroup8Widget()),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: null,
                                  bottom: null,
                                  width: 129.0,
                                  height: 116.0,
                                  child: TransformHelper.translate(
                                      x: -3.00,
                                      y: -410,
                                      z: 0,
                                      child: GeneratedGroup13Widget()),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
        )));
  }
}
