import 'package:flutter/material.dart';
import 'package:projyproject/shared/menu_drawer.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedProjyWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup14Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup15Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup16Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup17Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup19Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup20Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup21Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedRectangle4Widget.dart';

/* Component postProject
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPostProjectWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var scaffoldKey = GlobalKey<ScaffoldState>();
    return Scaffold(
        drawer: ClipRRect(
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(1000),
              bottomRight: Radius.circular(10)),
          child: MenuDrawer(),
        ),
        appBar: AppBar(
            key: scaffoldKey,
            leading: Builder(
              builder: (context) => IconButton(
                icon: Icon(Icons.menu_rounded),
                iconSize: 40,
                onPressed: () => Scaffold.of(context).openDrawer(),
              ),
            ),
            flexibleSpace: Container(
              decoration: new BoxDecoration(
                gradient: new LinearGradient(
                    colors: [
                      Color.fromARGB(255, 102, 59, 223),
                      Color.fromARGB(255, 135, 134, 231),
                    ],
                    begin: const FractionalOffset(0.0, 0.0),
                    end: const FractionalOffset(1.0, 0.0),
                    stops: [0.0, 1.0],
                    tileMode: TileMode.clamp),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                    ),
                    Positioned(
                      left: null,
                      top: -110,
                      right: -68.0,
                      bottom: null,
                      width: 192.0,
                      height: 207.0,
                      child: GeneratedEllipse8Widget(),
                    ),
                    Positioned(
                      left: null,
                      top: 40,
                      right: -4.8552703857421875,
                      bottom: null,
                      width: 96.85527038574219,
                      height: 44.0,
                      child: GeneratedProjyWidget(),
                    ),
                  ]),
            )),
        body: Material(
            child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 913.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 414.0,
                          height: 896.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 135, 134, 231),
                                  ),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 479.0,
                                  right: null,
                                  bottom: null,
                                  width: 63.0,
                                  height: 88.54545593261719,
                                  child: GeneratedGroup20Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: -14.0,
                                  right: -19.0,
                                  bottom: null,
                                  width: 56.0,
                                  height: 99.54545593261719,
                                  child: GeneratedGroup21Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: -22.0,
                                  bottom: -17.0,
                                  width: 119.0,
                                  height: 139.0,
                                  child: GeneratedGroup19Widget(),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 1,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 40.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width =
                                        constraints.maxWidth - 76.0;
                                    final double scaleX =
                                        width <= 0 ? 0 : (width / 338.0);

                                    final Widget child =
                                        GeneratedRectangle4Widget();
                                    return Stack(children: [
                                      Transform(
                                        transform: Matrix4(
                                            scaleX,
                                            0,
                                            0,
                                            0,
                                            0,
                                            1,
                                            0,
                                            0,
                                            0,
                                            0,
                                            1,
                                            0,
                                            37.0 * scaleX,
                                            32.0,
                                            0,
                                            1),
                                        alignment: Alignment.topCenter,
                                        child: SizedBox.expand(child: child),
                                      )
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 13.0,
                                  top: 95.0,
                                  right: 13.0,
                                  bottom: null,
                                  width: null,
                                  height: 372.0,
                                  child: GeneratedGroup14Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: 579.0,
                                  right: null,
                                  bottom: null,
                                  width: 388.0,
                                  height: 186.0,
                                  child: GeneratedGroup15Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: 485.0,
                                  right: null,
                                  bottom: null,
                                  width: 255.0,
                                  height: 75.0,
                                  child: TransformHelper.translate(
                                      x: -0.50,
                                      y: 0.00,
                                      z: 0,
                                      child: GeneratedGroup16Widget()),
                                ),
                                Positioned(
                                  left: null,
                                  top: 789.0,
                                  right: null,
                                  bottom: null,
                                  width: 255.0,
                                  height: 75.0,
                                  child: TransformHelper.translate(
                                      x: -1.50,
                                      y: 0.00,
                                      z: 0,
                                      child: GeneratedGroup17Widget()),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
        )));
  }
}
