import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedDonthaveanaccountCreateonehereWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedEllipse4Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedEllipse6Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedForgotpasswordWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedLine1Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedLine2Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedLoginWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedPasswordWidget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedProjyWidget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedloginscreenwidget/generated/GeneratedUsernameWidget1.dart';

/* Component loginscreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1140.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 425.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 102, 59, 223),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth - -93.0;
                                final double scaleX =
                                    width <= 0 ? 0 : (width / 518.0);

                                final double height =
                                    constraints.maxHeight - -360.0;
                                final double scaleY =
                                    height <= 0 ? 0 : (height / 1256.0);

                                final Widget child =
                                    GeneratedRectangle1Widget1();
                                return Stack(children: [
                                  Transform(
                                    transform: Matrix4(
                                        scaleX,
                                        0,
                                        0,
                                        0,
                                        0,
                                        scaleY,
                                        0,
                                        0,
                                        0,
                                        0,
                                        1,
                                        0,
                                        -48.0 * scaleX,
                                        -116.0 * scaleY,
                                        0,
                                        1),
                                    alignment: Alignment.topLeft,
                                    child: SizedBox.expand(child: child),
                                  )
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 212.0,
                              height: 219.0,
                              child: TransformHelper.translate(
                                  x: -143.50,
                                  y: -453.50,
                                  z: 0,
                                  child: GeneratedEllipse1Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 241.0,
                              child: TransformHelper.translate(
                                  x: 42.00,
                                  y: -401.50,
                                  z: 0,
                                  child: GeneratedEllipse3Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 233.0,
                              height: 194.0,
                              child: TransformHelper.translate(
                                  x: 178.00,
                                  y: -296.00,
                                  z: 0,
                                  child: GeneratedEllipse4Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 436.8754577636719,
                              height: 560.3885498046875,
                              child: TransformHelper.translate(
                                  x: -67.61,
                                  y: 193.76,
                                  z: 0,
                                  child: GeneratedRectangle2Widget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 88.6424560546875,
                              child: TransformHelper.translate(
                                  x: 66.50,
                                  y: -324.68,
                                  z: 0,
                                  child: GeneratedProjyWidget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 78.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 233.00,
                                  z: 0,
                                  child: GeneratedEllipse6Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 234.29998779296875,
                              height: 38.0,
                              child: TransformHelper.translate(
                                  x: 0.65,
                                  y: 367.00,
                                  z: 0,
                                  child: GeneratedForgotpasswordWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 62.0318603515625,
                              child: TransformHelper.translate(
                                  x: 1.50,
                                  y: 318.02,
                                  z: 0,
                                  child:
                                      GeneratedDonthaveanaccountCreateonehereWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 287.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 36.50,
                                  z: 0,
                                  child: GeneratedRectangle3Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 170.25860595703125,
                              height: 58.0,
                              child: TransformHelper.translate(
                                  x: 2.63,
                                  y: 235.00,
                                  z: 0,
                                  child: GeneratedLoginWidget()),
                            ),
                            // Positioned(
                            //   left: null,
                            //   top: null,
                            //   right: null,
                            //   bottom: null,
                            //   width: 198.0,
                            //   height: 61.0,
                            //   child: TransformHelper.translate(
                            //       x: 3.50,
                            //       y: 53.50,
                            //       z: 0,
                            //       child: GeneratedPasswordWidget1()),
                            // ),
                            // Positioned(
                            //   left: null,
                            //   top: null,
                            //   right: null,
                            //   bottom: null,
                            //   width: 253.0,
                            //   height: 84.0,
                            //   child: TransformHelper.translate(
                            //       x: 3.00,
                            //       y: -65.00,
                            //       z: 0,
                            //       child: GeneratedUsernameWidget1()),
                            // ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 300,
                              height: 150,
                              child: TransformHelper.translate(
                                x: 0.00,
                                y: 12.50,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextField(
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Username',
                                        hintText: 'Enter Username',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 300,
                              height: 200,
                              child: TransformHelper.translate(
                                x: -1.00,
                                y: 136.50,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    // width: 283,
                                    child: TextField(
                                      obscureText: true,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Password',
                                        hintText: 'Enter Password',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
