version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: socialnetwork
    ports:
      [3307:3307]
    volumes:
      ["./.data/db:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: socialnetwork